name = "oauth-do"
account_id = "b6641681fe423910342b9ffa1364c76d"
main = "index.js"
# usage_model = "unbound"
compatibility_date = "2022-06-21"
node_compat = true

tail_consumers = [{service = "tail", environment = "production"}]

services = [
  { binding = "CTX", service = "ctx-do", environment = "production" },
  { binding = "JWT", service = "jwt-do", environment = "production" }
]

kv_namespaces = [
  { binding = "USERS", id = "7c8468b38a1446a293ad78ece015f86c", preview_id = "e99589c478c24cb7b1c7f413c92db429" },
  { binding = "REDIRECTS", id = "fbf35fc28b9749b585c396d16843b0c9", preview_id = "d8a9be977354495784e3edf690b1b5fa" }
]

